[versions]
kotlin = "1.6.0"
room = "2.4.0-rc01"
datastore = "1.0.0"
compose = "1.1.0-beta04"
composeMaterial3 = "1.0.0-alpha02"
composeLottie = "4.2.1"
composeNavigation = "2.4.0-beta02"
composeHiltNavigation = "1.0.0-beta01"
composeViewmodel = "2.4.0"
appCompat = "1.4.0"
retrofit = "2.9.0"
okhttp = "4.9.1"
hilt = "2.38.1"
accompanist = "0.21.4-beta"
androidxCore = "1.7.0"
androidCoroutine = "1.5.2"
androidxWindow = "1.0.0-beta03"
splash = "1.0.0-alpha02"
material = "1.5.0-beta01"
protoGoogle = "4.0.0-rc-2"
protoWire = "4.0.0"
agp = "7.0.3"
navigationPlugin = "2.4.0-beta02"


[libraries]
# plugin kotlin
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
# plugin others
google-kspPlugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version = "1.5.30-1.0.0" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
squareup-wireGradlePlugin = { module = "com.squareup.wire:wire-gradle-plugin", version.ref = "protoWire" }
androidx-navigationGradlePlugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationPlugin" }

# kotlin
jetbrains-kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
# hilt
google-hiltGradlePlugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
google-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
google-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
# appCompat
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "appCompat" }
# room
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
# compose
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
androidx-compose-materialIcon = { module = "androidx.compose.material:material-icons-core", version.ref = "compose" }
androidx-compose-materialIconExtended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
androidx-lifecycle-viewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "composeViewmodel" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
androidx-hilt-navigationCompose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "composeHiltNavigation" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "composeLottie" }
# accompanist
google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
google-accompanist-navigation = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }
google-accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
# retrofit
squareup-retrofit-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
squareup-retrofit-converter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
# okhttp
squareup-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
# androidx others
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
# others
android-desugar = { module = "com.android.tools:desugar_jdk_libs", version = "1.1.5" }
jetbrains-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "androidCoroutine" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-splash = { module = "androidx.core:core-splashscreen", version.ref = "splash" }
androidx-window = { module = "androidx.window:window", version.ref = "androidxWindow" }
google-protobuf = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protoGoogle" }
google-material = { module = "com.google.android.material:material", version.ref = "material" }

# debugging compose
debugging-compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
# debugging okhttp
debugging-okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
# debugging others
debugging-chucker = { module = "com.github.chuckerteam.chucker:library", version = "3.5.2" }

# test
test-junit = { module = "junit:junit", version = "4.13.2" }
test-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "androidCoroutine" }
test-turbine = { module = "app.cash.turbine:turbine", version = "0.7.0" }
test-androidx = { module = "androidx.test.ext:junit", version = "1.1.3" }
test-robolectric = { module = "org.robolectric:robolectric", version = "4.5.1" }


[bundles]
networking = ["squareup-retrofit-retrofit", "squareup-retrofit-converter", "squareup-okhttp"]
