[versions]
kotlin = "1.5.30"
room = "2.3.0"
compose = "1.1.0-alpha04"
appCompat = "1.3.1"
retrofit = "2.9.0"
okhttp = "4.9.1"
hilt = "2.38.1"
accompanist = "0.19.0"


[libraries]
# plugin kotlin
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
# plugin others
google-kspPlugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version = "1.5.30-1.0.0" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version = "7.0.2" }
squareup-wireGradlePlugin = { module = "com.squareup.wire:wire-gradle-plugin", version = "3.7.0" }
androidx-navigationGradlePlugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version = "2.3.5" }

# kotlin
jetbrains-kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
# hilt
google-hiltGradlePlugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
google-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
google-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
# appCompat
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "appCompat" }
# room
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
# compose
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-materialIcon = { module = "androidx.compose.material:material-icons-core", version.ref = "compose" }
androidx-compose-materialIconExtended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
androidx-lifecycle-viewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version = "1.0.0-alpha07" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version = "2.4.0-alpha10" }
androidx-hilt-navigationCompose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0-alpha03" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version = "4.1.0" }
# accompanist
google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
google-accompanist-navigation = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }
google-accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
# retrofit
squareup-retrofit-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
squareup-retrofit-converter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
# okhttp
squareup-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
# androidx others
androidx-datastore = { module = "androidx.datastore:datastore", version = "1.0.0" }
# others
android-desugar = { module = "com.android.tools:desugar_jdk_libs", version = "1.1.5" }
jetbrains-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.3.9" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.5.0" }
androidx-splash = { module = "androidx.core:core-splashscreen", version = "1.0.0-alpha01" }
google-protobuf = { module = "com.google.protobuf:protobuf-javalite", version = "3.17.3" }
google-material = { module = "com.google.android.material:material", version = "1.5.0-alpha03" }

# debugging compose
debugging-compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
# debugging okhttp
debugging-okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
# debugging others
debugging-chucker = { module = "com.github.chuckerteam.chucker:library", version = "3.5.2" }

# test
test-junit = { module = "junit:junit", version = "4.13.2" }
test-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.5.1" }
test-turbine = { module = "app.cash.turbine:turbine", version = "0.6.0" }
test-androidx = { module = "androidx.test.ext:junit", version = "1.1.3" }
test-robolectric = { module = "org.robolectric:robolectric", version = "4.5.1" }


[bundles]
networking = ["squareup-retrofit-retrofit", "squareup-retrofit-converter", "squareup-okhttp"]
